name: GitHub/New_release_pipeline
on:
#  workflow_dispatch:
  workflow_run:
    workflows: ["GitHub/GitHub-ASP.NET-CI"]
    types: [completed]
jobs:
  Production:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    steps:
      - name: Sample
        run: echo Hello, world! 
#     # 497d490f-eea7-4f2b-ab94-48d9c1acdcb1@4: unsupported application type ($(Parameters.WebAppKind))
